---
title: "Interactive Maps with Leaflet in R - Chapter 2 - Plotting points"
author: "Braden Buchanan"
date: '2022-07-12'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#Install the package
install.packages('ipeds', repos=c('http://R-Forge.R-project.org', 'http://lib.stat.cmu.edu/R/CRAN'), dep=TRUE)
install.packages("XML")

#Load the package
library(magrittr)
library(ggplot2)
library(dplyr)
library(sf)
library(ggmap)
library(leaflet)
library(tidyverse)

```

```{r}
collegeData <- Most_Recent_Cohorts_All_Data_Elements

#renaming columns
collegeData %>%
  rename(
    STABBR = State
  )

collegeData

```

Number of California colleges or secondary education institutions
```{r}
collegesPerState <- collegeData %>%
  group_by(STABBR) %>%
  count() %>%
  arrange(desc(n))

summary(collegesPerState)

#converting column to int
collegesPerState[,2] <- sapply(collegesPerState[,2], as.numeric)
collegesPerState

collegesPerState %>%
  ggplot(aes(STABBR, n)) + 
  #include stat='identity' tells ggplot2 I will provide the y values for the barplot, rather than counting the aggregate number of rows for each   x value, which by default, is stat='count'
  geom_bar(stat='identity', fill = "steelblue") +
  geom_text(aes(label=n), vjust = 1.6, color = "white", size = 2.5) + 
  theme_minimal()
```
California has by far the most secondary school institutions in the country coming at 714. New York with 449. And Texas with 443.


```{r}
CASchools <- collegeData %>%
  drop_na() %>%
  filter(STABBR == "CA")

head(CASchools)
CASchools[,22:23] <- sapply(CASchools[,22:23], as.numeric)
CASchools[,22:23]

map %>%
  addMarkers(lng = CASchools$LONGITUDE, CASchools$LATITUDE)

```




